### ISSUE TITLE
NSLocationAlwaysUsageDescription now mandatory?

### ISSUE THREAD

**Issue by NiklasMerz** [apache/cordova-plugin-geolocation#111]
It looks like the key `NSLocationAlwaysUsageDescription `  is now mandatory, too.  Should we document this?

This is the warning Apple sent after uploading the app:
> "Missing Purpose String in Info.plist File. Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSLocationAlwaysUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting spring 2019, all apps submitted to the App Store that access user data will be required to include a purpose string.If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy)."

**Comment by lauvigne** [comment]
Is it the same as https://github.com/apache/cordova-plugin-geolocation/pull/105 ?

**Comment by NiklasMerz** [comment]
Partly. #105 adds a method to request always permission. But if the description clarifies that both descriptions are needed this is fine.

**Comment by Ajaxy** [comment]
I'm not using "always" mode, but Apple still complains about not having that `NSLocationAlwaysUsageDescription`.

**Comment by NiklasMerz** [comment]
That´s why I suggested adding something to the docs. Confuse me, too. 

`edit-config` like described does not work for me. I have to use `config-file`.

**Comment by sjokoladepudding** [comment]
I've found this article from apple:
https://developer.apple.com/documentation/corelocation/choosing_the_authorization_level_for_location_services/requesting_always_authorization

It says:

> Important
> You are required to include the NSLocationWhenInUseUsageDescription and NSLocationAlwaysAndWhenInUseUsageDescription keys in your app's Info.plist file. (If your app supports iOS 10 and earlier, the NSLocationAlwaysUsageDescription key is also required.) If those keys are not present, authorization requests fail immediately.

The NSLocationAlwaysAndWhenInUseUsageDescription is new to me. My app just got rejected, so I will try this too.

**Comment by piotr-cz** [comment]
There is a proposal on how to update documentation in #149

**Comment by breautek** [comment]
Fixed by https://github.com/apache/cordova-plugin-geolocation/pull/181
