### ISSUE TITLE
ERROR in node_modules/@ionic-native/geolocation/index.d.ts(2,10): error TS2305: Module

### ISSUE THREAD

**Issue by Eduardo-Vieira** [apache/cordova-plugin-geolocation#113]
ERROR in node_modules/@ionic-native/geolocation/index.d.ts(2,10): error TS2305: Module

I'm implementing in the app the lib but it gives this error

Ionic:

   ionic (Ionic CLI)          : 4.1.1 (/usr/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.3
   @angular-devkit/core       : 0.7.5
   @angular-devkit/schematics : 0.7.5
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : 1.0.7
   @ionic/schematics-angular  : 1.0.5

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (0 plugins total)

System:

   Android SDK Tools : 26.1.1 (/home/eduardo/Android/Sdk)
   NodeJS            : v8.11.4 (/usr/bin/node)
   npm               : 6.4.1
   OS                : Linux 4.15

**Comment by janpio** [comment]
> ERROR in node_modules/@ionic-native/geolocation/index.d.ts(2,10): error TS2305: Module

You notice it says `@ionic-native/geolocation`? You created an issue for the underlying Cordova plugin which has no influence over that. You should create an issue here: https://github.com/ionic-team/ionic-native/issues/
