### ISSUE TITLE
Frequency/Interval feature for `watchPosition`

### ISSUE THREAD

**Issue by siege-nnn** [apache/cordova-plugin-geolocation#115]
Hi,
Currently the plugin pulls updates every 1000ms (or 1s). Is there any intention to add frequency as a parameter?

(I can make a hack to ignore updates unless certain period had elapsed, but device will still drain the battery faster)

Thanks in advance,
Siege

**Comment by janpio** [comment]
What method is currently polling every 1000ms?
What platform?

**Comment by siege-nnn** [comment]
@janpio apologies, thought it was obvious.

watchPosition method is pulling every 1s.

Example:

      var options = {
        frequency: 3000, //<--- possible to add this parameter or similar?
        enableHighAccuracy: true
      };

      this.watchLocation = this.geolocation.watchPosition(options)
        .subscribe(position => {
//do something with position
....
        })

**Comment by luisfernando-rf** [comment]
Hello siege-nnn, I'm behind the same solution as yours this post, I see that there is no return to 19 days, did you get any solution to this problem?

Also I need a return of the updated positions in a time interval (minutes) and if possible in a range of meters traveled.

**Comment by luisfernando-rf** [comment]
????????

**Comment by luisfernando-rf** [comment]
Any return for kindness?

**Comment by siege-nnn** [comment]
Hey @luisfernando-rf , I have written a workaround code to reduce the "noise". Its been quite busy on this end. Will try to post my workaround later today or tomorrow.

Thanks

**Comment by luisfernando-rf** [comment]
Ok, thanks!

**Comment by siege-nnn** [comment]
@luisfernando-rf apologies for taking time to respond. I had to remove quite a bit of my other logic that I had in place and is not relevant. Let me know if you need assistance with the below, hopefully it would be self explanatory.

//declare before constructor
  locationLastUpdateTime = null
  locationMinUpdateFrequency = 5 * 1000 //~5s between user location updates
  private watchLocation;
  myPositionMarker = null;

  toggleLocationTrace() {

      try {
        this.watchLocation = this.geolocation.watchPosition(options)
          .filter((p) => p.coords !== undefined) //Filter Out Errors
          .subscribe(position => {
            console.log('position::', position, 'L:', position.coords.longitude + ' ' + position.coords.latitude);

            //only continue if its time to check
            let now = new Date();
            let duration: number
            try {
              duration = now.getTime() - this.locationLastUpdateTime.getTime()
            } catch (error) {
              duration = 999999999
            }
            if (this.locationLastUpdateTime == null || duration >= this.locationMinUpdateFrequency) {
              console.log('update is needed.::', duration)

                  let newPosition = { lat: position.coords.latitude, lng: position.coords.longitude }
                  if (this.myPositionMarker !== null) {
                    this.myPositionMarker.setPosition(newPosition);

                    if (this.followUserPosition == true) {
                      this.map.moveCamera({
                        target: newPosition,
                        //'zoom': 18,
                        //'bearing': 140
                      });
                    }
                  } else {
                    //create the marker
                    this.map.addMarker(
                      {
                        icon: 'red',
                        title: 'me',
                        //animation: google.maps.Animation.DROP,
                        draggable: false,
                        position: newPosition
                      })
                      .then(marker => {
                        this.myPositionMarker = marker
                      console.log('my marker::', this.myPositionMarker)
                      });
                  }
          
              this.locationLastUpdateTime = now;
            } else {
              //console.log('ignore position update::', duration);
            }


          });
      } catch (error) {
        console.log('unable to watch current location::', error)
      }
}

**Comment by luisfernando-rf** [comment]
I did it this way, but you're looking at me in error.

Error: 
"Uncaught TypeError: Failed to execute 'watchPosition' on 'Geolocation': The callback provided as parameter 1 is not a function."

`let watchLocation
let locationLastUpdateTime = null
let locationMinUpdateFrequency = 15 * 1000 

this.watchLocation = navigator.geolocation.watchPosition({enableHighAccuracy: true})
    .filter((p) => p.coords !== undefined)
    .subscribe(position => {
        console.log('position: ', position, 'L: ', position.coords.longitude + ' ' + position.coords.latitude)
        
        let now = new Date();
        let duration
        try {
            duration = now.getTime() - this.locationLastUpdateTime.getTime()
        } catch (error) {
            duration = 999999999
        }

        if (this.locationLastUpdateTime == null || duration >= this.locationMinUpdateFrequency) {
            console.log('Update is needed: ', duration)
            myLocation()
            this.locationLastUpdateTime = now;
        } else {
            console.log('Ignore position update: ', duration);
        }
    })`

**Comment by luisfernando-rf** [comment]
Your code should point to this error as well, since you only pass the option as a parameter. What is the solution?

**Comment by hamzahalvanaa** [comment]
@luisfernando-rf thanks. you saved my life.

**Comment by luisfernando-rf** [comment]
Great, good to have helped.

**Comment by breautek** [comment]
Frequency/Interval is not part of the [W3C Geolocation Spec](https://w3c.github.io/geolocation-api/), so there won't be any plans to implement this.

Most devices will yield an event once per second on a healthy GPS signal, but if you need less updates, then you can implement your own solution within the app to only propagate an event after some time as passed. Some examples are written above.
