### ISSUE TITLE
Geolocation Interval position

### ISSUE THREAD

**Issue by luisfernando-rf** [apache/cordova-plugin-geolocation#118]
Is there any function available in the plugin that updates the position of the coordinates in a certain time interval or a range of meters traveled, or something similar?

**Comment by luisfernando-rf** [comment]
???????

**Comment by luisfernando-rf** [comment]
Any return?

**Comment by ertgl** [comment]
May this help?
https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-geolocation/index.html#navigatorgeolocationwatchposition

**Comment by breautek** [comment]
There is nothing exposed through the plugin.

Speaking technically, it is possible on iOS as the native APIs do support filtering based on travel distance (this is hard-coded to be 5 meters when high accuracy is enabled).

Android however uses the webview's implementation of geolocation and doesn't give that level of granular control of when we receive updates. Even if we switch to the android native APIs, they don't offer a filter based on distance traveled like the iOS sdk does.
