### ISSUE TITLE
When getting location does'nt return anything or return empty error with a timeout (Android Oreo)

### ISSUE THREAD

**Issue by robert2206** [apache/cordova-plugin-geolocation#120]
```
this.geolocation.getCurrentPosition().then(location => {
    console.log(location);
}).cath(err => {
    console.log(err);
});
```

**Device:** Xiaomi Mi A2 Lite
**SO:** Android 8.1.0

> packages

"cordova-plugin-geolocation": "^4.0.1"
"ionic-angular": "^3.9.2",

**Comment by shokry055** [comment]
+1

**Comment by Motoralfa** [comment]
+1
I tried everything, setting the timeout in the options object, using navigator.geolocations, And the only that response is a null object...

**Comment by Motoralfa** [comment]
Well, i was reading documentation and i realize that error return a PositionError that has message and code as it say here
![captura](https://user-images.githubusercontent.com/10781270/48578370-2da32480-e8f8-11e8-88b4-dd1fca66d0fa.JPG)
try to change 
`console.log(err);`
to
`console.log(err.message);`
to see what it is wrong with the code. In my case it was a problem with the Secure Origins. Im sure most of the problems is related with that. I hope it can help you!

**Comment by robert2206** [comment]
@Motoralfa my error response is a empty object like this "{}"

**Comment by utiq** [comment]
Could you solve it? not working for me either, it doesn't even get into the error catch, it simple doesn't execute any log

**Comment by utiq** [comment]
Actually I just fixed 😬, just add { enableHighAccuracy: true }

**Comment by Hanzofm** [comment]
Same Problem

I am trying on a
```
Samsung J5 with android 7.0
cordova 8.0
cordova-android 7.1.2
```

The method
`this.geo.getCurrentPosition({timeout: 30000, maximumAge: 0, enableHighAccuracy: true})`

Jumps to catch with no error descrition
`{}`

What would be wrong?

**Comment by Motoralfa** [comment]
> Same Problem
> 
> I am trying on a
> 
> ```
> Samsung J5 with android 7.0
> cordova 8.0
> cordova-android 7.1.2 / 7.11 / 7.00
> ```
> The method
> `this.geo.getCurrentPosition({timeout: 30000, maximumAge: 0, enableHighAccuracy: true})`
> 
> Jumps to catch with no error descrition
> `{}`
> 
> What would be wrong?

Did you try to catch the error with `console.log(error.message)` instead of `console.log(error)`. Try this even if it seem to be a null objects, it can return a message of the problem

**Comment by Hanzofm** [comment]
@Motoralfa You are right

this is the error:

`Only secure origins are allowed (see: https://goo.gl/Y0ZkNV).`

I have tried on ionic without `--livereload` flag and not gets an error but the position returned is:

`console.log(JSON.stringify(pos.coords))`


`{}`

Also I have tried console.log(JSON.stringify(pos.coords)) with the same result

**Comment by breautek** [comment]
`Error` objects are weird, and messages are not printed out when you simply console log the message. Their properties behave as if they are on the prototype.

You need to use `error.message` to see the actual error message as stated at https://github.com/apache/cordova-plugin-geolocation/issues/120#issuecomment-440980371

 > Only secure origins are allowed (see: https://goo.gl/Y0ZkNV).

If you're using the ionic webview, you must use `https` [scheme](https://github.com/ionic-team/cordova-plugin-ionic-webview#scheme)

**Comment by rehman22** [comment]
> Actually I just fixed 😬, just add { enableHighAccuracy: true }

i guess i dont have luck

**Comment by ImAbhishekTomar** [comment]
same issue foe me can someone please help. 

```
getCurrentGeoPosition = async (): Promise<Geoposition> => {
    try {
      const options: GeolocationOptions = {
        timeout: 30000,
        maximumAge: 0,
        enableHighAccuracy: true,
      };
      await this.geolocation
        .getCurrentPosition(options)
        .then((position) => Promise.resolve(position))
        .catch((error) => Promise.reject(error));
    } catch (error) {
      console.log(error.message);
      return Promise.resolve(error);
    }
  };
```
