### ISSUE TITLE
Askin permission when need

### ISSUE THREAD

**Issue by Kasun002** [apache/cordova-plugin-geolocation#121]
Iam using this plugin with this permission

<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-feature android:name="android.hardware.location.gps" />

how to ask permission when we need only.

In my situation it ask location when app initally load

**Comment by jcesarmobile** [comment]
It should ask when you call the code to get location.
So as you didn't show your code I'll assume you call it when the app initially load and that's why it asks.
