### ISSUE TITLE
Unable to obtain location information.

### ISSUE THREAD

**Issue by guolulu13204101** [apache/cordova-plugin-geolocation#122]
phone:nubia NX569H
android:6.0.1

The execution method console.log no information.

 //定位
  public getGPS(){
    let that=this;
    this.geolocation.getCurrentPosition().then((resp) => {
      console.log(1,resp.coords.latitude,resp.coords.longitude);
    }).catch((error) => {
      console.log('Error getting location', error);
    });

  }

**Comment by utiq** [comment]
Could you solve it? not working for me either, it doesn't even get into the error catch, it simple doesn't execute any log

**Comment by utiq** [comment]
Actually I just fixed 😬, just add { enableHighAccuracy: true }

**Comment by Hanzofm** [comment]
I am trying on a
```
Samsung J5 with android 7.0
cordova 8.0
cordova-android 7.1.2 / 7.11 / 7.00
```

The method
`this.geo.getCurrentPosition({timeout: 30000, maximumAge: 0, enableHighAccuracy: true})`

Jumps to catch with no error descrition
`{}`

What would be wrong?

**Comment by guolulu13204101** [comment]
I added { enableHighAccuracy: true },but there is no return.

**Comment by breautek** [comment]
I've made a detailed answer on #119 on why obtaining GPS may be slow or not possible. Using `{ enableHighAccuracy: true` like @maitscha suggested may help, but that option will only work if the user has the Android's GPS settings configured in a certain way. Unfortunately this is also something outside of Cordova or the apps control.

https://github.com/apache/cordova-plugin-geolocation/issues/119#issuecomment-463897045

**Comment by breautek** [comment]
Closing due to lack of response.
