### ISSUE TITLE
Phonegap Build Log: Plugin doesn't support this project's cordova-android version

### ISSUE THREAD

**Issue by potatoboy1999** [apache/cordova-plugin-geolocation#124]
I'm working on a phonegap project that needs to show the current position of the user. The plugin works fine when tested on a browser or on the PhoneGap App for Android, but when i build the apk for android on PhoneGap Build the function navigator.geolocation.getCurrentPosition runs the error function with:

`Code: 2, Message: application does not have sufficient geolocation permissions.`

And on the **PhoneGap Build Log** I see this, which kinda tells me something wrong is happening when installing the plugin in the apk.

```
PLUGIN OUTPUT
--------------------------------------------------------------------------------
Fetching plugin "cordova-plugin-geolocation@^4.0.1" via npm
Installing "cordova-plugin-geolocation" at "4.0.1" for android
Plugin doesn't support this project's cordova-android version. cordova-android: 6.1.2, failed version requirement: >=6.3.0
Skipping 'cordova-plugin-geolocation' for android
```

I thought that i just had to update the cordova-android version but when i run **`cordova platforms`** i get:

```
cordova platforms
Installed platforms:
  android 6.4.0
  browser 5.0.4
  ios 4.5.5
Available platforms:
  osx ~4.0.1
  windows ~6.0.0
```
So my cordova-android is actually different when i send it to the build.

**Comment by brodybits** [comment]
Looks like a good question for the PhoneGap Build forum.

>
I suspect you hit a pitfall where the default CLI version is quite behind
on PhoneGap Build: https://build.phonegap.com/current-support

You should configure to use a newer version.

I would highly recommend you try upgrading to the latest version on both
your machine and PhoneGap Build of possible. We have resolved some npm
audit issues and made a number of other updates.

**Comment by potatoboy1999** [comment]
Ok, thanks, i'll be posting there as well

**Comment by potatoboy1999** [comment]
Changing the CLI version was the solution. The plugin is installing fine now. Thanks 😄 👍
