### ISSUE TITLE
Geocoder.geocode returns 'Request denied' status

### ISSUE THREAD

**Issue by ViCoastLLC** [apache/cordova-plugin-geolocation#135]
navigator.geolocation.getCurrentPosition  returns success but, geocoder.geocode returns status -'Request denied' 

Code:
navigator.geolocation.getCurrentPosition(onSuccess, onError);
                            function onSuccess(position) {
                                var geocoder;
                                geocoder = new google.maps.Geocoder();
                                var latlng = new google.maps.LatLng(position.coords.latitude, position.coords.longitude);
                                geocoder.geocode(
                                    { 'latLng': latlng },
                                    function (results, status) {
                                        if (status == google.maps.GeocoderStatus.OK) {
//mycode
}

**Comment by ViCoastLLC** [comment]
> What platform? What version? What device?

both android and iOS

**Comment by breautek** [comment]
Realised this is old now but this plugin has nothing to do with geocoders so I don't think this is the best place to ask this kind of question. For this reason I'm closing this issue.
