### ISSUE TITLE
Error: Can't resolve all parameters for AppComponent: (?).

### ISSUE THREAD

**Issue by EliuFlorez** [apache/cordova-plugin-geolocation#138]
![error-geo](https://user-images.githubusercontent.com/784787/50528832-87753d80-0aa5-11e9-9011-6fcd765b155d.png)

**Comment by janpio** [comment]
Not related to this plugin.

**Comment by mariejoseebassil** [comment]
had the same problem using this plugin, so @janpio please re-open the issue

**Comment by breautek** [comment]
> had the same problem using this plugin, so @janpio please re-open the issue

The callstack and error provided does not come from this plugin whatsoever, or the cordova codebase for that matter. You're asking the wrong people for assistance regarding this issue.

You'll probably be better off asking about this issue at https://github.com/angular/angular and so people who has experience with angular can provide their expertise.

**Comment by btr-simbu** [comment]
`import {Geolocation} from '@ionic-native/geolocation/ngx';`

This was a main issue for me. Check your import statements once. Because I'm using PhpStorm IDE it autocompletes Geolocation with no Imports. It might be helpful.
