### ISSUE TITLE
Location does not turn on

### ISSUE THREAD

**Issue by rashnk** [apache/cordova-plugin-geolocation#139]
When the function gets called the app ask for permission to use location, but it does not turn on location even I press 'allow',
navigator.geolocation.getCurrentPosition(onSuccess, onError);

but it works when manually turn on location
Android 7.1.1
8.1.2 (cordova-lib@8.1.1)
Geolocation Plugin 4.0.1

![screenshot_20181230-161111](https://user-images.githubusercontent.com/12730428/50546833-4b340f80-0c54-11e9-9106-5a3d852d6b32.jpg)

**Comment by hvaughan3** [comment]
If the device has its location services turned off, no app on the device is able to change that setting, only the user can. The user must manually enable location services for your app to access the device's location.

**Comment by rashnk** [comment]
Im trying to understand, so what does the above permission request box does?. and do we need to use some other plugin to turn on the location service?

**Comment by rashnk** [comment]
Thanks all for the info, but I already added the above mentioned plugin and got it working, :smile:

**Comment by Arxi** [comment]
@rashnk which plugin? could you post your solution? thanks!

**Comment by rashnk** [comment]
I wil post after reaching home

**Comment by rashnk** [comment]
`
        cordova.plugins.locationAccuracy.request(
          function() {
            console.log("testhigh success");
            setTimeout(function() {
              getPosition();
            }, 1500);
          },
          function() {
            console.log("error");
          },
          cordova.plugins.locationAccuracy.REQUEST_PRIORITY_HIGH_ACCURACY
        );
`

`
function getPosition() {
        navigator.geolocation.getCurrentPosition(
          function(position) {
            var latitude = position.coords.latitude;
            var longitude = position.coords.longitude;
           }
        )
}
`

**Comment by rashnk** [comment]
```
package.json


    "dependencies": {
        "cordova-admob-sdk": "^0.13.1",
        "cordova-android": "^7.0.0",
        "cordova-android-play-services-gradle-release": "^2.0.0",
        "cordova-plugin-admob-free": "^0.13.0",
        "cordova-plugin-geolocation": "^4.0.1",
        "cordova-plugin-network-information": "^2.0.1",
        "cordova-plugin-request-location-accuracy": "^2.2.3",
        "cordova-plugin-whitelist": "^1.3.3",
        "cordova-promise-polyfill": "0.0.2"
    },
    "cordova": {
        "plugins": {
            "cordova-plugin-whitelist": {},
            "cordova-plugin-admob-free": {},
            "cordova-plugin-request-location-accuracy": {},
            "cordova-android-play-services-gradle-release": {
                "PLAY_SERVICES_VERSION": "15.+"
            },
            "cordova-plugin-geolocation": {},
            "cordova-plugin-network-information": {}
        },
        "platforms": [
            "android"
        ]
    }
```

**Comment by robirobinson** [comment]
> ```
> 
>         cordova.plugins.locationAccuracy.request(
>           function() {
>             console.log("testhigh success");
>             setTimeout(function() {
>               getPosition();
>             }, 1500);
>           },
>           function() {
>             console.log("error");
>           },
>           cordova.plugins.locationAccuracy.REQUEST_PRIORITY_HIGH_ACCURACY
>         );
> 
> function getPosition() {
>         navigator.geolocation.getCurrentPosition(
>           function(position) {
>             var latitude = position.coords.latitude;
>             var longitude = position.coords.longitude;
>            }
>         )
> }
> ```

Hi rashnk, was it worked?  where can i download those additional plugins to enable location in the device automatically

**Comment by Almya** [comment]
I don't understand why this plugin ask for permission before trying to access current location but don't ask the user to turn his GPS on. Because of this, none of onSuccess or onError callbacks are triggered.
