### ISSUE TITLE
How to support background mode?

### ISSUE THREAD

**Issue by tavor8** [apache/cordova-plugin-geolocation#140]
It seems this plugin doesn't support background mode, while testing in android8.1, while the app in background mode, this plugin can't record location info at all,  is there anyone knows how to solve this?

**Comment by paredesivan** [comment]
install the plugin cordova-plugin-background-mode and put thiss lines on your controller

        try {
               cordova.plugins.backgroundMode.onactivate = function () {                                 
                        cordova.plugins.backgroundMode.disableWebViewOptimizations();           
                     };
                     } catch (e) {
           }

**Comment by breautek** [comment]
Cordova plugin doesn't support background currently. The main challenge is not all devices allow webview javascript to be ran in the background.

There are however plugins available that is background friendly, like mentioned above.
