### ISSUE TITLE
Fix NSLocationWhenInUseUsageDescription documentation (ios12+ config.xml)

### ISSUE THREAD

**Issue by vousys** [apache/cordova-plugin-geolocation#142]
Guys for Phonegap users, in config.xml  fix the documentation, they should add the platform="ios" to the code, like this:

```
<edit-config  platform="ios"  target="NSLocationWhenInUseUsageDescription" file="*-Info.plist" mode="merge">
    <string>need location access to find things nearby</string>
</edit-config>
```

instead of

```

<edit-config   target="NSLocationWhenInUseUsageDescription" file="*-Info.plist" mode="merge">
    <string>need location access to find things nearby</string>
</edit-config>
```

**Comment by janpio** [comment]
This repo does not have any documentation regarding usage in Phonegap. What are you referring to?

**Comment by vousys** [comment]
Here https://github.com/apache/cordova-plugin-geolocation#ios-quirks the plugin says   "To add this entry into the info.plist, you can use the edit-config tag in the config.xml like this:"
And for phonegap users or any other cordova plugin users, like ionic, they need to add the  platform="ios"  to get this variable compile.

Is only add this to the code :  platform="ios"

**Comment by janpio** [comment]
Ah, so what you write also applies to all normal Cordova users?
Is it possible that the docs assumed you put it inside a `<platform name="ios">...</platform>` element? Does this also work?

**Comment by vousys** [comment]
no, that seems to not be working anymore, because yesterday Apple reject me an app who has that syntax `<platform name="ios">...</platform>`

**Comment by timbru31** [comment]
Closing as this is about PhoneGap and not Cordova - a "fix" for PhoneGap users is included in this issue, too.
