### ISSUE TITLE
Support for cordova-osx

### ISSUE THREAD

**Issue by ameykshirsagar** [apache/cordova-plugin-geolocation#143]
Hi,
I am building an application for OSX using cordova-osx platform. However when I try to get geolocation coordinates. I am getting an error
code : 1
message : User denied Geolocation

I however feel that through this plugin with wrapper around [CoreLocation ](https://developer.apple.com/documentation/corelocation) APIs can solve the problem.

Thank you in advance

**Comment by breautek** [comment]
OSX has been deprecated so this feature request is obsolete.
