### ISSUE TITLE
object(...) is not a function

### ISSUE THREAD

**Issue by akildemir** [apache/cordova-plugin-geolocation#144]
When I use the get getCurrentPosition function of geoLocation, typescript gives the error Object(...) is not a function. I have recently(last 2 days) run into same issue when try to use the ionic-firebase and solved it by installing an older version of firebase.

Anyways, I know that this is version issue. Probably happening because of ionic team is slowly making it is way to ionic v4 completely. So Do you guys know what is the last version of ionic-geolocation that is compatible with ionic V3 app and how can I install it? I saw 0.3.12 in the README.md but it seems they recommend it for older version of cordova.

My current package versions :  
Ts : ~2..6.2
Angular : ^5.2.11
Cordova : 7

Thanks in advance!

**Comment by zyzmoz** [comment]
Today I had the same problem, and the unique solution I found was downgrade the plugin version to ^4.0.1;

**Comment by akildemir** [comment]
Thanks fro answer but It is been long time I this. and forget the close the top
