### ISSUE TITLE
How to track location in background on iOS?

### ISSUE THREAD

**Issue by projjwalg** [apache/cordova-plugin-geolocation#145]
This plugin works really well with on iOS. But I would like to use this plugin to track location even when the app is in the background on iOS. Is there any way to implement background location with this plugin on iOS? If yes, then is there any working examples available for this?

**Comment by ruisilva450** [comment]
Have you seen https://github.com/mauron85/cordova-plugin-background-geolocation?

**Comment by Taxi4you** [comment]
> Have you seen https://github.com/mauron85/cordova-plugin-background-geolocation?

Is this a free plugin? I have heard that it's free only for DEBUG, but PRODUCTION required a license (Android only)..

**Comment by janpio** [comment]
See https://github.com/mauron85/cordova-plugin-background-geolocation/blob/master/LICENSE

**Comment by Taxi4you** [comment]
Yes I saw this, but this plugin seems to be the same as: https://github.com/transistorsoft/cordova-background-geolocation-lt and this is not a free one, they charge money for having a license.

So, are they the same plugins or not? Hope you have some information about this. Thanks.

**Comment by janpio** [comment]
Why do you think they are the same? Also: We can't give you legal advice on any non Apache Cordova plugins - you have to talk to the people that own those repositories for binding answers.

**Comment by Taxi4you** [comment]
Okay probably they are not, my mistake. Sure. Thanks.

**Comment by breautek** [comment]
Background is not currently supported. The main challenge with this is not all devices allow javascript to be ran in the background. So even if we broadcast events, you may only be able to respond to them once your app returns to the foreground.

We have a feature ticket for this at https://github.com/apache/cordova-plugin-geolocation/issues/165 so I'll be closing this issue.
