### ISSUE TITLE
Android location permissions not being requested using Cordova 9

### ISSUE THREAD

**Issue by ekrapfl** [apache/cordova-plugin-geolocation#147]
# Bug Report

## Problem
I am trying out using Cordova 9, and most things seem to be working alright, but the geolocation plugin is not adding the appropriate `uses-permission` tags to the android manifest file.

Note: this works fine if I revert back `cordova-cli@8` and `cordova-android@7`

### What is expected to happen?
Adding `cordova-plugin-geolocation` should add the appropriate permissions to the manifest file and allow requesting location in the app.
```
<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
```

### What does actually happen?
Adding `cordova-plugin-geolocation`does not add the appropriate permissions, and thus, my app is not able to request a GPS location.

### Environment, Platform, Device
Android (have not attempted iOS yet)

### Version information
I am using
```
"cordova-plugin-geolocation": "4.0.1"
"cordova-android": "^8.0.0"
"cordova": "^9.0.0"
"ionic": "4.12.0"
```

## Checklist

- [ x] I searched for existing GitHub issues
- [x ] I updated all Cordova tooling to most recent version
- [x ] I included all the necessary information above

**Comment by ekrapfl** [comment]
After further discussion on the other issue I posted, this clearly does not seem like the correct place for this one.  Does not seem at all related to cordova-plugin-geolocation.  Closing the issue here.

**Comment by alvarofelipe12** [comment]
This happened to me but i solved this moving the code that used the geolocation plugin all over the end of the platform.ready() listener and then it started to ask properly for permissions using cordova 9 but my platform was android 7.0.0. Hope that this data helps!
