### ISSUE TITLE
Documentation for gelocation plugin should be updated to meet new apple rules about location access

### ISSUE THREAD

**Issue by iphonedeveloper99** [apache/cordova-plugin-geolocation#149]
# Feature Request

## Motivation Behind Feature

Apple identified some issues without specified NSLocationAlwaysUsageDescription in info,plist, so the documentation for geolocation plugin is missed some informations, please update the documentation and add these rules to it:

edit-config target="NSLocationAlwaysAndWhenInUseUsageDescription" file="*-Info.plist" mode="merge">
          string>Need location access to find things nearby. /string>
      /edit-config>
       edit-config target="NSLocationWhenInUseUsageDescription" file="*-Info.plist" mode="merge">
       string>Need location access to find things nearby. /string>
      /edit-config>
      edit-config target="NSLocationAlwaysUsageDescription" file="*-Info.plist" mode="merge">
       string>Need location access to find things nearby./string>
     /edit-config>

(*** please note that i removed the start of codes because github not allowed these, so please add < in the first of each code)

Apple will send an email about issues found if you don't add the previous rules to info.plist.

Message from apple: 
Missing Purpose String in Info.plist File - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSLocationAlwaysUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data will be required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy).

## Feature Description

Please add these rules to the documentation:
/edit-config target="NSLocationAlwaysAndWhenInUseUsageDescription" file="*-Info.plist" mode="merge">
          string>Need location access to find things nearby. /string>
      /edit-config>
       edit-config target="NSLocationWhenInUseUsageDescription" file="*-Info.plist" mode="merge">
       string>Need location access to find things nearby. /string>
      /edit-config>
      edit-config target="NSLocationAlwaysUsageDescription" file="*-Info.plist" mode="merge">
       string>Need location access to find things nearby./string>
     /edit-config>

(*** please note that i removed the start of codes because github not allowed these, so please add < in the first of each code)

**Comment by piotr-cz** [comment]
Please see https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown on how to format code in markdown
