### ISSUE TITLE
Can not get location

### ISSUE THREAD

**Issue by kotromeo** [apache/cordova-plugin-geolocation#156]
### Issue Type

- [ X] Bug Report

## Description
Plugin can not get location even if everything is enabled in system. Android Xiaomi MI 6
, android 8.0.0 OPR1.170623.027

**Comment by timbru31** [comment]
Thanks a lot for your issue, however the issue template exists for a reason 😉 
It helps us to debug the issue further and to provide a solution much faster. With important information missing, we unfortunately can't help you.

Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information.

**Comment by breautek** [comment]
I've created a gist that covers the top reasons why you may not receive GPS results in a timely fashion which can be read [here](https://gist.github.com/breautek/d6231fa33d6942c269296546892afb5e)

**Comment by breautek** [comment]
If the issue is not edited to include the information that the template requests in the next couple of days or so I'll treat this issue as abandoned and it will be closed.
