### ISSUE TITLE
TypeError: Cannot read property 'getCurrentPosition' of undefined

### ISSUE THREAD

**Issue by fax1ty** [apache/cordova-plugin-geolocation#157]
# Bug Report
### What is expected to happen?
I wanted to get the data

### What does actually happen?
```
Error in Success callbackId: Geolocation1100061559 : TypeError: Cannot read property 'getCurrentPosition' of undefined
 
processMessage failed: Error: TypeError: Cannot read property 'getCurrentPosition' of undefined
 
processMessage failed: Stack: TypeError: Cannot read property 'getCurrentPosition' of undefined
at win (./plugins/cordova-plugin-geolocation/www/android/geolocation.js:35:16)
at Object.callbackFromNative (./cordova.js:291:58)
at processAndroidEvent (./cordova.js:986:17)
at _class.<anonymous> (./cordova.js:1005:9)
at ./node_modules/tabris/tabris.min.js:1:27083
at _class.trigger (./node_modules/tabris/tabris.min.js:1:27247)
at _class.$trigger (./node_modules/tabris/tabris.min.js:1:63505)
at _class._trigger (./node_modules/tabris/tabris.min.js:1:63275)
at Tabris._notify (./node_modules/tabris/tabris.min.js:1:70355)
 
processMessage failed: Message: S01 Geolocation1100061559 sOK
```

### Code
```typescript
 navigator.geolocation.getCurrentPosition(position => console.log(position), e => console.error(e));
```

``` console.log(navigator.geolocation);``` returns the following
```js
{ getCurrentPosition: [Function: getCurrentPosition],
watchPosition: [Function: watchPosition],
clearWatch: [Function: clearWatch] }
```

### Version information
Cordova: Cordova 8.1.2, [cordova-plugin-geolocation](https://github.com/apache/cordova-plugin-geolocation/) - master branch
Other Frameworks: [Tabris.js](https://github.com/eclipsesource/tabris-js/) 3.0.0
Android 8.1.0

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
You might already be doing this but... make sure you are only calling the API **after** the [deviceready](https://cordova.apache.org/docs/en/9.x/cordova/events/events.html#deviceready) event fires.

If that doesn't help, then I'd suggest creating a minimal project that reproduces the issue. Instructions can be found [here](https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md)

**Comment by fax1ty** [comment]
> You might already be doing this but... make sure you are only calling the API **after** the [deviceready](https://cordova.apache.org/docs/en/9.x/cordova/events/events.html#deviceready) event fires.

In Tabris, all API requests are made after `deviceready`.

> If that doesn't help, then I'd suggest creating a minimal project that reproduces the issue. Instructions can be found [here](https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md)

Should there be a Tabris framework in the minimal project? Or should I use pure Cordova?

**Comment by janpio** [comment]
If this works in pure Cordova, but not in Tabris, then this is probably more a issue for/of Tabris, right?

**Comment by breautek** [comment]
Should be pure Cordova. If the issue only happens in Tabris, it will probably be best to raise the issue with the Tabris team.

**Comment by fax1ty** [comment]
All right, I'll send the issue there. I was hoping you could tell me something here.

**Comment by fax1ty** [comment]
Yeah, problem on Tabris side. Thx, guys

**Comment by janpio** [comment]
Thanks for the update @fax1ty!

Tabris is pretty interesting by the way, especially that they still use Cordova plugins although the UI is fully native seems interesting.
