### ISSUE TITLE
iOS CDVLocation.m error on Crashlytics

### ISSUE THREAD

**Issue by lkonzen-garupa** [apache/cordova-plugin-geolocation#161]
### Issue Type

- [x] Bug Report
- [ ] Feature Request
- [ ] Support Question

## Description
I'm getting errors registered on crashlytics for iOS. With occurrences on all the different devices (Iphone 6, 7,....) 

## Information

```
Fatal Exception: NSGenericException
0  CoreFoundation                 0x1832e2d8c __exceptionPreprocess
1  libobjc.A.dylib                0x18249c5ec objc_exception_throw
2  CoreFoundation                 0x1832e23c0 -[__NSSingleObjectEnumerator initWithObject:]
3  Garupa                         0x1030b4640 -[CDVLocation returnLocationError:withMessage:] (CDVLocation.m:312)
4  Garupa                         0x1030b3178 -[CDVLocation startLocation:] (CDVLocation.m:117)
5  Garupa                         0x1030b3a64 __27-[CDVLocation getLocation:]_block_invoke (CDVLocation.m:222)
6  libdispatch.dylib              0x182bd4aa0 _dispatch_call_block_and_release
7  libdispatch.dylib              0x182bd4a60 _dispatch_client_callout
8  libdispatch.dylib              0x182bdbb84 _dispatch_queue_override_invoke$VARIANT$mp
9  libdispatch.dylib              0x182be1cac _dispatch_root_queue_drain
10 libdispatch.dylib              0x182be19fc _dispatch_worker_thread3
11 libsystem_pthread.dylib        0x182f07fac _pthread_wqthread
12 libsystem_pthread.dylib        0x182f07b08 start_wqthread
```
### Command or Code

```js
navigator.geolocation.watchPosition(
                getPositionSuccess,
                function (err) {...},
                {
                    enableHighAccuracy: true,
                    timeout: 5000,
                    maximumAge: 5000
                }
            )
```
### Environment, Platform, Device

Occurs on iOS on all devices.

### Version information

Cordova version: 8.1.2
cordova-plugin-geolocation: 4.0.1
Ionic framework: 1
Ionic cli: 4.12.0

## Checklist

- [x] I searched for already existing GitHub issues about this
- [-] I updated all Cordova tooling to their most recent version
- [x] I included all the necessary information above

**Comment by ssuhane** [comment]
When this issue will be fixed any guesses? 
We are also facing the same issue.

**Comment by timbru31** [comment]
Is this reproducible in a new, plain Cordova app? A minimal reproduction repository would really help to debug and later fix this issue. More information on how to create one: https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md

**Comment by breautek** [comment]
Closing as stale.
