### ISSUE TITLE
Position is retrieved only after reseting the GPS services.

### ISSUE THREAD

**Issue by Taxi4you** [apache/cordova-plugin-geolocation#163]
# Bug Report

## Problem
Android:
When I am trying to retrieve the position for first time, just immediately after enabling location service it works - I get the position coords.
But when back again after some minutes or after changing position (20 km of change) and try again it doesn't work. It just gets timeout error when timeout is getting executed.
If you set 5 seconds or 30 seconds, no matter it just waiting until timeout and location is not getting retrieved. The "fix" for this issue is to completely turn of location services in the device and re open them and try again. Then after very very quick time, something like 300ms there a valid response with the position's coords.

iOS Xcode simulator (7, 8, 8s, iphonex etc...):
When using watchPosition, the position is getting retrieved first, 
next beat after 5 seconds, there is an error of timeout. No matter what. Seems like Xcode simulator doesn't support the watchPosition interval. Is it?

### Command or Code
  ```
let positionWatcher = navigator.geolocation.watchPosition(
    GeolocationSuccessCallback, // first time works
    GeolocationFailCallback, // second time, not works.
    {
      timeout: 10000, 
      enableHighAccuracy: true
    }
  )
```

### Environment, Platform, Device
Android Samsung Galaxy S7 device (not simulator).
Xcode's simulators - I have tried something like 5 or 6 iPhones versions.
iOS platform 9.0

### Version information
Cordova: Cordova CLI, Cordova Platforms, Cordova Plugins 
Other Frameworks: Ionic Framework and CLI version
Real device, Xcode etc.

## Checklist

- [x ] I searched for existing GitHub issues
- [ x] I updated all Cordova tooling to most recent version
- [x ] I included all the necessary information above

**Comment by breautek** [comment]
Please read my [gist](https://gist.github.com/breautek/d6231fa33d6942c269296546892afb5e) on why you may not be receiving GPS points as expected. 

Most of the time this is a combination of the phone not configured to use AGPS (so it relies soley on GPS satellites) & the device being in a poor  environment such as in a large buildings or basements.

**Comment by breautek** [comment]
Closing due to lack of response.
