### ISSUE TITLE
Rarely find position in Android

### ISSUE THREAD

**Issue by Taxi4you** [apache/cordova-plugin-geolocation#166]
# Bug Report

## Problem
**watchPosition** is extremely rarely detects the position on real Android device while walking/driving/moving.

### What is expected to happen?
To find the user's position even if he moves (walking/driving/cycling).

### What does actually happen?
Timeout error in trying to get the position of the user. When the user is in office or doesn't moving the position is getting retrieved after 0.32 ms (very quick). But when the user moves with the device - nothing, changes are 1/20 that position will be found.

## Information
You can try 20 times and maybe one of them will successfully find the position and return with a successful callback.
The rest of them will return fail callback with timeout error.

### Command or Code
I have tested on real device on Android Samsung Galaxy S7 only so far.
I really hope this severe issue doesn't happening on iOS too..

### Environment, Platform, Device
Android.

### Version information
I don't know. Just my Samsung Galaxy S7.

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
This issue comes up frequently and most of the time it is due to restrictive settings on the phone.

I've created a gist that covers 2 main reasons why you may get unresponsive or inaccurate GPS readings which can be read [here](https://gist.github.com/breautek/d6231fa33d6942c269296546892afb5e)

**Comment by breautek** [comment]
If there are no response over the next couple of days or so then I'm going to assume this issue has been resolved and I'll close the ticket.
