### ISSUE TITLE
No Types

### ISSUE THREAD

**Issue by janpio** [apache/cordova-plugin-geolocation#167]
This plugin is missing the type definitions we usually have for TypeScript users.

**Comment by timbru31** [comment]
Types shouldn't be needed, since this is basically the same as https://developer.mozilla.org/en-US/docs/Web/API/Geolocation

**Comment by janpio** [comment]
And TypeScript knows about these by default? Or the editors like e.g. VSCode?

**Comment by timbru31** [comment]
They are in the [lib.dom.d.ts](https://github.com/microsoft/TypeScript/blob/master/lib/lib.dom.d.ts) which is _"included"_ with TypeScript. And I would assume that every web project has the DOM definitions loaded :D
