### ISSUE TITLE
once user denied permission to track location, then it's not requesting permissions

### ISSUE THREAD

**Issue by kotran88** [apache/cordova-plugin-geolocation#169]
```
 this.geo.getCurrentPosition(options).then((success)=>{
      this.lat=success.coords.latitude;
      this.lng=success.coords.longitude;
      window.alert("done");
    });
    }).catch((e)=>{
      console.log("failed");
      console.log(e);
}
```

I really don't understand why it's not requesting permission to user after once user disallow permission at first time....

how can I solve problem?

**Comment by breautek** [comment]
On iOS, if a user denies permission, then iOS will block that app from requesting permissions. The user must go to the Settings app themselves to enable permissions for your app.

Android has the same behaviour, except that android has a checkbox to "Do not ask me again" on their permission models. If the user checked that checkbox and deny permissions, then the android behaviour is exactly the same as iOS.

In these cases, the app cannot request the same permission again. 

If you're just testing, on Android you can completely uninstall the app, and reinstall it which should reset the permission status back to a "not requested" state. Additionally if you're comfortable using `adb` tool, you can use `adb shell pm revoke com.your.package android.permission.WRITE_EXTERNAL_STORAGE` (replacing the permission to the permission you want to reset) or `adb shell pm reset-permissions` to reset permissions on all apps. On iOS, if it is an app deployed via XCode, then I think uninstalling the app the permissions will reset

Personally in my apps, I use the [diagnostics plugin](https://github.com/dpa99c/cordova-diagnostic-plugin) which gives me APIs to not only request appropriate permissions, but to also check the permission status. Then I provide proper user feedback depending on the permission status.

**Comment by breautek** [comment]
If I don't hear a response over the new couple of days or so I'll assume the question has been answered and the issue will be closed.
