### ISSUE TITLE
Timeout expired error on some devices

### ISSUE THREAD

**Issue by ioclaudio** [apache/cordova-plugin-geolocation#170]
I have a problem with an Ionic4 app that uses geolocation on some devices with Android 9.

Running this code on a One Plus One mobile phone, the device asks for permission to use the geolocation.
If I click on "Confirm" the plugin returns the error:
```
PositionError {code: 3, message: "Timeout expired"}
code: 3
message: "Timeout expired"
__proto__: PositionError
```

This is the code I'm using:
`    
	const geo_options = {
		enableHighAccuracy: true,
		timeout: 20000,
		maximumAge: 0
	};

	this.geolocation.getCurrentPosition(geo_options).then((resp) => {
		console.log('coordinates OK: ', this.coordinates);
		....
	}).catch((error) => {
		console.log(error)
		...

	}
`

In the settings of the mobile phone, I can see that the app has permission for using the geolocation.
So why it doesn't give the geolocation coordinates?
How can I debug better this situation?

This is the setup of the system:
`
>ionic info
Ionic:
   Ionic CLI                     : 5.2.1 
   Ionic Framework               : @ionic/angular 4.3.0
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.8
   @ionic/angular-toolkit        : 1.5.1
Cordova:
   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0, ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.0, (and 11 other plugins)
Utility:
   cordova-res : 0.6.0
   native-run  : 0.2.2
System:
   Android SDK Tools : 26.1.1 
   NodeJS            : v10.15.3
   npm               : 6.9.0
   OS                : Windows 10
`

These are the Cordova plugins installed:
`
>cordova plugin list
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-insomnia 4.3.0 "Insomnia (prevent screen sleep)"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.1.0 "cordova-plugin-ionic-webview"
cordova-plugin-ios-disableshaketoedit 1.0.0 "iOS Disable Shake to Edit"
cordova-plugin-mauron85-background-geolocation 3.0.3 "CDVBackgroundGeolocation"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
phonegap-plugin-barcodescanner 8.0.1 "BarcodeScanner"
`

**Comment by breautek** [comment]
The timeout, as you probably know... occurs when the GPS doesn't provide you with a location update within a reasonable amount of time (defined by the `timeout` parameter).

I've created a [gist](https://gist.github.com/breautek/d6231fa33d6942c269296546892afb5e) that you can read that might help.

**Comment by breautek** [comment]
If there are no response over the next couple of days or so then I'm going to assume this issue has been resolved and I'll close the ticket.

**Comment by ioclaudio** [comment]
Yes, excuse me, after a reset to manufacturer settings the mobile started working, so I think it was a problem of the device.

**Comment by Hideiki** [comment]
About this detail, I solve my problem changing the permission:

`cordova.plugins.permissions.requestPermission(permissions.ACCESS_FINE_LOCATION);`

I wish some help this
