### ISSUE TITLE
getCurrentPosition on my mobile device returns only 9 digits. How can I get more digits (42.123456789101112123)?

### ISSUE THREAD

**Issue by emostackfm** [apache/cordova-plugin-geolocation#174]
### Issue Type

- [ ] Bug Report
- [ ] Feature Request
- [x] Support Question

## Checklist

- [x] I searched for already existing GitHub issues about this
- [ ] I updated all Cordova tooling to their most recent version
- [x] I included all the necessary information above

**Comment by emostackfm** [comment]
I am developing a mobile application where I need to get mobile phone location coordinates. I am using cordova geolocation plugin but it returns me latitude and longitude with 9 digits (42,1234567), which is not very correct. I need more digits like 42,123456789101112? Do you know how can I achieve this?

**Comment by breautek** [comment]
Not very accurate? 

15 places after the decimal is like centimeters of accuracy.

Most mobile phones only have the capability of giving you a GPS point with about 3-5 meter accuracy. And to get a meter accuracy, you only need approximately 5 digits after the decimal.

I've provided a proof case here:
https://runkit.com/embed/9v79e9hlwjlc

**Comment by jcesarmobile** [comment]
You can try passing the enableHighAccuracy option.
The geolocation plugin just uses the webview implementation, so if even with that option you don’t get a good accuracy report it to google.
