### ISSUE TITLE
Can't get controls display on IOS

### ISSUE THREAD

**Issue by Steco17** [apache/cordova-plugin-geolocation#176]
Hello guys am working the 2.6.2 version of the plugin  but i can't display the map controls on IOS. The same google map controls works on Android (6.4>) but not IOS .
Any solution to this?

**Comment by timbru31** [comment]
Thanks a lot for your issue, however the issue template exists for a reason 😉 
It helps us to debug the issue further and to provide a solution much faster. With important information missing, we unfortunately can't help you.

Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information.

**Comment by breautek** [comment]
Additionally this plugin has nothing to do with Google Maps, so you're probably asking the wrong community.

**Comment by breautek** [comment]
If the issue hasn't been updated to include the information the template asks over the next couple of days or so, then I'll treat this issue has abandoned and the issue will be closed.
