### ISSUE TITLE
position.coords.accuracy is inaccurate by 200+ feet

### ISSUE THREAD

**Issue by caleb87** [apache/cordova-plugin-geolocation#182]
The position.coords.accuracy value has been inaccurate by up to 200+ feet. 

For example, the accuracy showed 27 meters (89 feet), but in reality the coordinate was about 310 feet away. This was in a city, with no tall buildings nearby, no trees within 75 feet (very few trees at all), and clear skies. 

Not sure if it matters, but this was while using enableHighAccuracy:true

Most of the time, the coordinate is accurate to within 20-30 feet and the actual coordinate is within the range. Sometimes it'll bounce out of the accuracy area though for 5-15 seconds roughly.

Reproduction has only been done on the following platform:
Pixel 4 device, Android 10
cordova-plugin-geolocation version 4.0.2
phonegap cli 9.0.0 / cordova cli 9.0.0
Android Studio 3.5.1

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
While `enableHighAccuracy:true` is required if you want anything within meters accuracy (most phones are capable giving ~5meters)... there is still the user location settings that unfortunately the developer has very little control over.

For example, `enableHighAccuracy` doesn't do a whole lot unless if the phone has high accuracy enabled in their location settings, including Wifi/bluetooth scanning. Each android manufacturer may have different location settings, and different devices have different GPS hardware with different capabilities, so mileage will vary here.

And of course, the surrounding environment plays a big role in accuracy as well. My workplace is in a city, but no tall buildings or mountains, etc, but the office is in a basement and that's enough to throw the GPS off.

**Comment by caleb87** [comment]
Thanks for the input!

My main issue isn't the accuracy of the coordinate itself, but the "accuracy" value provided. To take it to a greater scale, if the GPS accuracy says 20 feet, and in reality it's 2 miles away, that creates a major problem. On the other hand, if the accuracy states within 2 miles, and the coordinate is 2 miles away, then that works.

**Comment by breautek** [comment]
I see.

The accuracy reading is suppose to be the amount of meters within the real location with a 95% confidence level.

So if you have a reading of 20 feet, or 6 meters... but the given location is 2 miles, or ~3200 meters away from the real location, then obviously that is wrong.

Unfortunately, there isn't anything Cordova can do about this problem as Cordova doesn't have a geolocation implementation for android, it just uses the browser implementation. For android, this plugin just simply exposes the permission model.

If this is in anyway consistently reproducible, I'd consider making a bug report to the chrome webview team.

**Comment by breautek** [comment]
@caleb87 can this be closed?
