### ISSUE TITLE
Plugin doesn't work when wrapped inside a service on iOS

### ISSUE THREAD

**Issue by carstenbaumhoegger** [apache/cordova-plugin-geolocation#184]
# Bug Report

## Problem
We use Ionic 4 with Angular for our application.
When I wrap the plugins functionality inside a service, everything works fine on Android. On iOS though, no location can be obtained.
When I copy the methods from the used service 1:1 into the component that uses the service, everything works as expected on Android and iOS.

### What is expected to happen?
Geolocation can be obtained through a centralized service inside the application

### What does actually happen?
On iOS, no location usage permission request is fired. The only thing that is returned from the plugin is `code: 2`.

### Command or Code

I wrapped the `watchPosition` method inside of a simple Angular service. Basically it executes the following method:
```js
  private startPositionWatching () {
    if (this.positionWatchSubscription == null) {
      this.positionWatchSubscription = this.geolocation.watchPosition({ enableHighAccuracy: true, maximumAge: 15000 }).subscribe(async (position: any) => {
        // do something with position
      }, (error) => {
        console.error('watch position error', error);
      });
    }
  }
```

### Environment, Platform, Device

iOS 12 / 13 (didn't test older versions).
Can be reproduced on physical device and in the simulator.

### Version information

```
Ionic:

   Ionic CLI                     : 5.4.12 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.11.5
   @angular-devkit/build-angular : 0.803.20
   @angular-devkit/schematics    : 8.3.20
   @angular/cli                  : 8.3.20
   @ionic/angular-toolkit        : 2.1.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0, ios 5.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.1, (and 16 other plugins)

Utility:

   cordova-res (update available: 0.8.1) : 0.6.0
   native-run (update available: 0.3.0)  : 0.2.2

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.2
   NodeJS     : v12.13.1 (/usr/local/bin/node)
   npm        : 6.12.1
   OS         : macOS Catalina
   Xcode      : Xcode 11.2.1 Build version 11B53
```
```
cordova-plugin-geolocation 4.0.2 "Geolocation"
```

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by sithwarrior** [comment]
I would assume this is a timing issue.

Your service is probably starting, before the plugin is ready, and should be wrapped inside of platform ready. If you are using Ionic, you could use the platform.ready [https://ionicframework.com/docs/angular/platform](url)

if you are using basic cordova, you could use cordova deviceready
[https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-device/index.html](url)

**Comment by carstenbaumhoegger** [comment]
hey @sithwarrior ,
that's a good idea, I'll try to start the position watching when `platform.ready()` is fired!

**Comment by carstenbaumhoegger** [comment]
this indeed solved the problem, thank you!
