### ISSUE TITLE
GPS not working if the user presses the power button > Android 5

### ISSUE THREAD

**Issue by EnemyArea** [apache/cordova-plugin-geolocation#185]
### What is expected to happen?
On Android 5, the plugin will still send data, even if the user presses the power button.

### What does actually happen?
We testet on Android 8 and it will not send data if the user presses the power button

### Version information
Cordova: Cordova CLI, Cordova Platforms, Cordova Plugins 
9.0.0 (cordova-lib@9.0.1)
Android 5/8
with plugin for wakelock: at.gofg.sportscomputer.powermanagement
https://github.com/Viras-/cordova-plugin-powermanagement

Operating System, Android Studio, Xcode etc.
- Visual Studio Code

**Comment by breautek** [comment]
Does it only occur with the powermanagement plugin? Are you able to replicate the issue with a very basic cordova app?

https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md

**Comment by breautek** [comment]
Closing as stale.
