### ISSUE TITLE
Documentation seems misleading about whether or not the plugin is necessary

### ISSUE THREAD

**Issue by ekrapfl** [apache/cordova-plugin-geolocation#186]
# Bug Report
Looking at this in the documentation:
```
This API is based on the W3C Geolocation API Specification, and only executes on devices that don't already provide an implementation.
```

I assumed that because my app runs on latest Safari in iOS (which provides an implementation of the geolocation API), that I would no longer require this plugin.  I removed the plugin, but iOS no longer allows access to geolocation.

## Problem
If you remove the plugin and deploy on iOS (using a non-https url), you will get the following error when trying to use `navigator.geolocation`:
```
[blocked] Access to geolocation was blocked over insecure connection to ionic://localhost
```

### What is expected to happen?
According to the documentation, I would have expected to be able to use the `navigator.geolocation` API (without this plugin) for any Cordova application.  For iOS, however the plugin is still required because of the limitation Apple has placed on the geolocation API on insecure URLs.  Furthermore, the documentation seems to indicate that the plugin does nothing at all if the API is available in the browser.  Clearly, that is not true.  It appears that it clobbers the API, whether it exists or not (and I am glad it does :D).

### Environment, Platform, Device
An Ionic app
iOS only

### Version information
I am using @ionic/angular 4.11.1, and cordova-plugin-ionic-webview 4.0.0
```
Ionic:

   Ionic CLI                     : 5.4.4
   Ionic Framework               : @ionic/angular 4.11.1
   @angular-devkit/build-angular : 0.803.13
   @angular-devkit/schematics    : 8.3.13
   @angular/cli                  : 8.3.13
   @ionic/angular-toolkit        : 2.1.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.0, (and 17 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 0.2.9 (update available: 0.3.0)

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.2
   NodeJS     : v10.16.3 (/usr/local/Cellar/node@10/10.16.3/bin/node)
   npm        : 6.9.0
   OS         : macOS Catalina
   Xcode      : Xcode 11.3 Build version 11C29
```

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
It could be more clear because i believe the plugin is still required to mark capabilities and/or provide the native permission modal, regardless if the browser provides a geolocation api or not.

For example the plugin doesn't actually implement the geolocation api for android, but it does handle the permissions.
