### ISSUE TITLE
Android X - Handle location permission when user selects- "Allow only when using the app"

### ISSUE THREAD

**Issue by meghanadixit1** [apache/cordova-plugin-geolocation#188]
# Bug Report

### What is expected to happen?
Prior to Android X, when getCurrentPosition() is called, And user clicks on Allow, we used to get the current location.
Now with Android X, we get new dialog with 3 options - 
Allow
Allow only when using the app
Deny

When the second option is selected, and the location is off from the device settings, Nothing happens - neither error nor success.

### What does actually happen?
We should get appropriate response from the method, so that we can handle the error gracefully.

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by wayne12304** [comment]
With Android11, we get a dialog with 3 options -
Only this time
While using the app
Deny

When user select [Only this time] or [While using the app], getCurrentPosition() callback error with timeout

**Comment by rogisolorzano** [comment]
Also seeing this issue on Android 11. When I select 'Only this time' or 'While using the app', `getCurrentPosition` is timing out.

**Comment by spinninghamster** [comment]
Any fix for this?

**Comment by breautek** [comment]
Fixed by https://github.com/apache/cordova-plugin-geolocation/pull/250
