### ISSUE TITLE
Error with permissions when app starts for the first time

### ISSUE THREAD

**Issue by piernik** [apache/cordova-plugin-geolocation#190]
I'm using `cordova-plugin-geolocation@4.0.2` with `@ionic/angular@5.0.4` and `@ionic-native/geolocation@5.21.6`. 

When device is ready I ask for GPS localization:
`this.platform.ready().then(() => { this.geolocation.watchPosition({});}`

When I install android app for the first time it asks me for localization permissions but then in background I 'm getting error with no permissions.
When I grant permissions I'm still not getting position - so I press `refresh` button which triggers `this.geolocation.watchPosition({});` once again but now I'm getting `Timout` error.
I have to close app and start it once again.
Is it a bug? Is there a solution?

**Comment by Maqsyo** [comment]
Try to first get the current position (geolocation.getCurrentPosition(onSuccess, onError)and on success create the watcher.
Hadn't problems with that

**Comment by piernik** [comment]
I solved it that way. But it is bug in my opinion

**Comment by breautek** [comment]
What platform(s) does this occur on?

**Comment by piernik** [comment]
Android@7

**Comment by breautek** [comment]
> Android@7

`cordova-android@7`? or Android OS 7?

**Comment by piernik** [comment]
cordova-android@7

**Comment by breautek** [comment]
The latest version at the time of writing is `cordova-android@9`. cordova-android@7 is quite old. I'd try upgrading first. If the issue persists, we will need an [example app that reproduces the issue](https://github.com/apache/cordova-plugin-geolocation/issues/190). Do note that the example app should be as minimal as possible, we cannot debug apps that uses frameworks. It should contain vanilla js/cordova libraries only.

**Comment by piernik** [comment]
I switched to capacitor so I'll close this...
