### ISSUE TITLE
GeoLocation not responding back

### ISSUE THREAD

**Issue by DanishaRegil** [apache/cordova-plugin-geolocation#195]
We are currently using Ionic plugin for geoLocation 
and its quite surprising to see  the plugin is not responding back.
We are either getting the data nor the error 

Tried in multiple projects as well as multiple device.

The only log available in logcat related to geoPlugin is  
D/GeolocationPlugin: We are entering execute

Can someone help on this

**Comment by breautek** [comment]
If you're using the emulator, then you have to manually trigger GPS events using the emulator UI.

On devices, there are many reasons why you may not be receiving GPS updates. If you're using course mode (high accuracy disabled), then you may need to actually travel a significant distance  before receiving an update.

If you're using high accuracy, then your environment is the biggest factor. Being inside a large concrete office building for example hinders the phone's ability to communicate with the GPS satellites. Ensuring the phone has A-GPS features enabled (wifi/bluetooth/mobile network) assistance will help reduce reliance on the GPS satellites. These settings will vary by device, but I don't think I've seen a modern phone without these features. Do note that these are user settings in the OS, and not controlled by the app.

This issue doesn't include our issue template so I'll be closing this issue. If you think you've found a bug please open a new ticket and do not delete the template and instead fill it out. If you require further assistance, then a more appropriate place for support is our [slack](http://slack.cordova.io/).
