### ISSUE TITLE
Geolocation in android SKD 6.0

### ISSUE THREAD

**Issue by chongfei111** [apache/cordova-plugin-geolocation#197]
If can't use this plugin under the 6.3.0, how can I get geolocation in lower version than 6.3.0?

**Comment by Ahhsan** [comment]
how are you trying ?

**Comment by timbru31** [comment]
Thanks a lot for your issue, however the issue template exists for a reason. 😊   
It helps us to debug the issue further and to provide a solution much faster. With important information missing, we unfortunately can't help you.

Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information.
