### ISSUE TITLE
Error in windows version

### ISSUE THREAD

**Issue by AlexandreInsua** [apache/cordova-plugin-geolocation#198]
Hi guys!
I apologize. I don't use the template because this is a very specific question.
I'm using this plugin. When I generate the apk file, app works in android devices, but when I export to a .exe file (I need a windows devices version for) using electron I get this error: 
network location provider. no response receiver

Any idea?
Thanks.

**Comment by timbru31** [comment]
> but when I export to a .exe file

Could you please clarify this? Is the cordova-windows platform not working or are you using the cordova-electron platform?

**Comment by AlexandreInsua** [comment]
Sorry for delay. I just checked your answer. I haven't receipt any notification from github. I was using cordova-electron platform but I'm testing diferents ways to generate a viable .exe. 
I close this issue, if I had any problem, I'd post again.
