### ISSUE TITLE
Not working on android device Vivo Y12

### ISSUE THREAD

**Issue by jitendrabeyond** [apache/cordova-plugin-geolocation#203]
geolocation.getCurrentPosition method failed to return the current position on device Vivo Y12 device. Even i gives the permissions. Please see the attached screenshots

![image](https://user-images.githubusercontent.com/67774941/86434741-d8f62c80-bd1b-11ea-9739-12ee82489e5f.png)
![image](https://user-images.githubusercontent.com/67774941/86434769-eb706600-bd1b-11ea-9b20-99ace578c732.png)

**Comment by timbru31** [comment]
Thanks a lot for your issue, however the issue template exists for a reason. 😊   
It helps us to debug the issue further and to provide a solution much faster. With important information missing, we unfortunately can't help you.

Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information.

**Comment by jitendrabeyond** [comment]
Hello, @timbru31  Can you please help me to solve the issue?

**Comment by breautek** [comment]
As Tim said, we are missing a lot of crucial information to provide any real assistance.

Things like:

- Cordova CLI version
- Cordova plugin version
- Cordova platform version
- Android OS version
- The actual error message that is thrown to the error callback

Additionally this may help: https://gist.github.com/breautek/d6231fa33d6942c269296546892afb5e

**Comment by jitendrabeyond** [comment]
Hello @timbru31,

Please see the screenshot for the things:

![image](https://user-images.githubusercontent.com/67774941/86719833-10c5e280-c042-11ea-9d9f-91486c5a22d0.png)
 

Android OS version: 9
The actual error message that is thrown to the error callback: returning only empty object like '{ }'

**Comment by breautek** [comment]
There error is probably an `Error` class, you can't `JSON.stringify` it. You lose the prototype members when you do.

**Comment by jitendrabeyond** [comment]
![image](https://user-images.githubusercontent.com/67774941/86720628-d6107a00-c042-11ea-8096-12262f3d0885.png)

**Comment by breautek** [comment]
Well you can't alert objects. You need to use an actual debugger to see the object. You need to use Google Chrome and go to `chrome://inspect` for remote debugging. You can then either breakpoint or read the console output.

https://developers.google.com/web/tools/chrome-devtools/remote-debugging/webviews#open_a_webview_in_devtools

**Comment by jitendrabeyond** [comment]
**Yes, I debug it and getting the error "Timeout expired".**


geoLocationoptions: any =
   {
     enableHighAccuracy: true,
     timeout: 30000,
     maximumAge: 0
   }

I am passing the options in method getCurrentPosition.

 geolocation.getCurrentPosition(geoLocationoptions)

**Comment by breautek** [comment]
Timeout means the GPS receiver was unable to find a GPS point within your timeout setting, which in your case is 30 seconds.

This is possible for a host of different reasons, which I talked about [here](https://gist.github.com/breautek/d6231fa33d6942c269296546892afb5e). Unfortunately, most of these reasons are outside of the app's control.
