### ISSUE TITLE
basic usage in an app

### ISSUE THREAD

**Issue by sticcino** [apache/cordova-plugin-geolocation#206]
Hi,

just trying out the plugin, no means Js expert

create cordova test app, installed the geolocation plugin
all good.

copied the www files to the test app js folder, but receive the following error when reviewing the console.

Uncaught ReferenceError: require is not defined at geolocation.js:22

in index.html, i added the script as follows:

        src="cordova.js"><
        src="js/index.js"><
        src="js/geolocation.js"><

any help appreciated

**Comment by timbru31** [comment]
Thanks a lot for your issue, however this channel is for bug and feature requests, not for support. 😊  
You can try asking on [StackOverflow](https://stackoverflow.com/questions/tagged/cordova) or in our [Slack community](http://slack.cordova.io).
