### ISSUE TITLE
Getting diffeerent location data if i am still on same place. is there any solution for IOS?

### ISSUE THREAD

**Issue by herobarua** [apache/cordova-plugin-geolocation#207]
@breautek 
Hello sir,
Here is screenshot:
![location_accuracy](https://user-images.githubusercontent.com/1532317/90726926-4e29bb00-e2e4-11ea-9a3b-d626ecf2343d.jpg)

Below config used to get one time location using  
getCurrentPosition function but it return every time different data for ios

let geo_location_options = <any>{
      enableHighAccuracy: true,
      timeout: 10000,
      maximumAge: 0
    };

**Comment by ipehimanshu** [comment]
yes we have same issue in ios ,
some time accuracy shows 200 and some time 10, so 
if we want to make it some consistent, then is there any solution?

Thanks in advance

**Comment by breautek** [comment]
Please don't ping users that haven't engaged in the discussion.

The accuracy reading means the GPS event is confident the the given point is within that radius in meters.

So in other words when you have a 60 accuracy reading means that the GPS is confident that the given point is within a 60 meters radius of your true location. So the lower this number is, the more confident and accurate the GPS point is.

Having a high accuracy reading means there is interference with the GPS. This is usually environment related issues (such as being in a concrete building).

Apart of using the `highAccuracy` api option, there isn't anything you can programmatically do to improve accuracy. The `highAccuracy` option enables the mode to be more aggressive, (generally up to a 5m accuracy radius in my experience), but there are other variables at play; namely GPS settings on the device itself, and the environment of the device. Both of these variables are outside of your control.

If accuracy is a concern, the developer is expected to look at the accuracy reading, and determine if that GPS point is safe to use. It can also be used to provide a weak gps indicator. I talk more about accuracy issues on my [gist](https://gist.github.com/breautek/d6231fa33d6942c269296546892afb5e).

Based on your error message, where you're trying to use GPS to determine if the user is in a shop, which I assume is in some kind of building. This kind of usage is usually geolocation's weak point. For best results, you need to be outside with a clear open skies. You will likely not get results that is satisfactory using geolocation technology. [Indoor Positioning System](https://register.apple.com/indoor) may be a better choice of technology for this purpose. I'm not sure if Google has something equivalent for Android, but I would be surprised if they didn't. I haven't used this technology myself, so I can't really provide pointers, but it looks like you can provide a floor plan of your store, and I'm assuming there is a more reliable way to determine if the user is actually inside or outside of the store. Apache doesn't offer plugins for this API, so you'll also have to find a third-party plugin, or may have to create one yourself.

**Comment by herobarua** [comment]
Thanks for fast reply and clarification.

**Comment by ipehimanshu** [comment]
thanks for you reply
