### ISSUE TITLE
npm gets version 4.0.2 instead of 4.1

### ISSUE THREAD

**Issue by gwhenne** [apache/cordova-plugin-geolocation#215]
# Bug Report

## Problem

`cordova build` gets wrong version

### What is expected to happen?

It should get the current version via npm, which is 4.1.

### What does actually happen?

It gets version 4.0.2.

## Information

From debug output of `cordova build`:
```
No version specified for cordova-plugin-geolocation, retrieving version from config.xml
No version for cordova-plugin-geolocation saved in config.xml or package.json
Attempting to use npm info for cordova-plugin-geolocation to choose a compatible release
Ignoring invalid version in cordova-plugin-geolocation cordovaDependencies: 5.0.0 (must be a single version <= latest or an upper bound)
Calling plugman.fetch on plugin "cordova-plugin-geolocation@4.0.2"
```

### Command or Code
In config.xml:
```
<plugin name="cordova-plugin-geolocation" source="npm">
```
Run
```
cordova build android  --device --debug --verbose --nohooks-.
```

### Environment, Platform, Device
Building on MacOs

### Version information
```
Cordova Packages:

    cli: 10.0.0
        common: 4.0.2
        create: 3.0.0
        lib: 10.0.0
            common: 4.0.2
            fetch: 3.0.0
            serve: 4.0.0

Project Installed Platforms:

    android: 9.0.0

Project Installed Plugins:

    cordova-plugin-geolocation: 4.0.2
    cordova-plugin-splashscreen: 6.0.0
    cordova-plugin-statusbar: 2.4.3
    cordova-plugin-whitelist: 1.3.4

Environment:

    OS: macOS Mojave 10.14.6 (18G6020) (darwin 18.7.0) x64
    Node: v12.18.3
    npm: 6.14.7
```

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
This is intentional. Version 4.1.0 is tagged for release but is not released yet. It's currently in the vote process. Assuming the vote is successful, you should be seeing the actual release in the upcoming days. You can [subscribe](https://cordova.apache.org/contact/) to our mailing list if you want to be notified the vote results.
