### ISSUE TITLE
Any solution for [Deprecation] getCurrentPosition() and watchPosition() no longer work on insecure origins ?

### ISSUE THREAD

**Issue by danielcollione** [apache/cordova-plugin-geolocation#223]
Hi, i emulate my app ionic on device Android (Chrome live reload), when i use this geolocation plugin, it report "Error getting location GeolocationPositionError {code: 1, message: "Only secure origins are allowed (see: https://goo.gl/Y0ZkNV)."}". Sorry, i'm new...

capacitor-runtime.js:3146: [Deprecation] getCurrentPosition() and watchPosition() no longer work on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.

**Comment by timbru31** [comment]
Thanks a lot for your issue, however the issue template exists for a reason. 😊   
It helps us to debug the issue further and to provide a solution much faster. With important information missing, we unfortunately can't help you.

Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information.
