### ISSUE TITLE
iOS 14.5 AppTrackingTransparency?

### ISSUE THREAD

**Issue by parksmart-dev** [apache/cordova-plugin-geolocation#227]
Anyone had apple reject their application for this issue?  First time, so it must be something new they've introduced.

**Comment by timbru31** [comment]
How is the App Tracking Transparency Framework related to this specific plugin?

**Comment by parksmart-dev** [comment]
I only use this plugin in the app, they said it was tracking people and need that permission.  I've resubmitted and it's passed now, so all good.

**Comment by dslima90** [comment]
It is probably related to the app privacy information you provided in App Store Connect. If you do not collect data in order to track the user, you should review your app privacy information. This issue is probably not related to any plugin you use.

**Comment by breautek** [comment]
App Tracking Transparency (ATT) is related to using external tracking sources to identify users or devices for the purposes of marketing.

This may indirectly apply to this plugin if you collect location data and share it with a data broker, for the purpose of attaching location information to a tracker identifier; in which case you should honour the request of the user if they deny tracking.

While ATT may be indirectly related, I feel like implementing any kind of ATT prompts in this plugin is out of scope, and probably should be handled by a more generic API or plugin instead.

Using geolocation for the purpose of providing functionality to your app is not related to ATT; however you still need to provide usage justification, e.g: "This app requires location to automatically show your position on Map"

This can be accomplished by using the below config for example:

```xml
<edit-config target="NSLocationWhenInUseUsageDescription" file="*-Info.plist" mode="merge">
    <string>This allows TotalPave PCI to center the map to your location to make it easier to select nearby sections.</string>
</edit-config>
<edit-config target="NSLocationAlwaysUsageDescription" file="*-Info.plist" mode="merge">
    <string>This allows TotalPave PCI to center the map to your location to make it easier to select nearby sections.</string>
</edit-config>
```

**Comment by dslima90** [comment]
I guess a lot of people missunderstood what User Tracking means when filled apple privacy information on AppStore Connect. They probably corelated User Tracking to GPS Tracking. I am guessing a lot of people may be presented with this issue and @breautek answer explains very well what User Tracking means in this context. So, just to make it clearer, if you dont collect user data to share with a third party for marketing purposes and are getting this issue, check the privacy information you submitted to apple on your AppStore Connect.
