### ISSUE TITLE
geoocation not returning anything when device has no internet connection

### ISSUE THREAD

**Issue by jagatb880** [apache/cordova-plugin-geolocation#228]
this.geolocation.getCurrentPosition(this.options).then((resp) => {

this above method doesn't return any thing when there is no internet connection in old redmi and lenovo mobiles, but when internet if on it returns the lat and long.

this issue arises on 

    "cordova-plugin-geolocation": "^4.1.0",

    "@ionic-native/geolocation": "^5.32.0",
    
import { Geolocation } from '@ionic-native/geolocation/ngx';

but the same isssue is not happending in old versions of plugin

    "cordova-plugin-geolocation": "^4.0.1",

    "@ionic-native/geolocation": "^4.18.0",

import { Geolocation } from '@ionic-native/geolocation';

**Comment by breautek** [comment]
If the device doesn't have an active GPS satellite fix, it can take a significant amount of time (>= 15 mins sometimes) to obtain a GPS location from the satellites.

A-GPS features, if supported & enabled, solves that issue, (using wifi, bluetooth, cellular towers, internet etc). If you have older phones, it's possible that they don't have complete A-GPS features implemented and disabling internet forces it to solely rely on GPS satellites.

Also note that Cordova doesn't maintain an actual geolocation implementation for Android. The plugin is purely for managing the required permissions and android project configuration. The geolocation implementation is provided by the system webview itself, so any bugs with the webview geolocation API needs to be brought to the Chromium team. (But in this case, I think on those devices, when internet is disabled, it solely relies on GPS satellites which is accurate, but extremely slow)

I also have a bigger spiel on location accuracy / timeout reasons that may be relevant to you: https://gist.github.com/breautek/d6231fa33d6942c269296546892afb5e

I'm closing this issue as I don't believe this is a bug with `cordova-plugin-geolocation`. If you can be sure you're in a healthy location spot (e.g. other apps can obtain GPS fine in the same device configuration) and still have problems, I'd recommend trying to isolate the issue by using a simple [cordova reproduction app](https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md) without using the ionic framework. With the sample reproduction app that contains only cordova packages we can provide better insight.

Kind regards,
Norman
