### ISSUE TITLE
Ionic - Position error:application does not have sufficient geolocation permission

### ISSUE THREAD

**Issue by pirpy76** [apache/cordova-plugin-geolocation#245]
Using Ionic : 
- Cordova CLI 11.0.0
- Cordova Platform 9.1.0
- Ionic CLI                     : 5.4.16 (C:\PP\Ionic2020\node_modules\ionic)
   Ionic Framework               : @ionic/angular 6.0.4
   @angular-devkit/build-angular : 13.0.4
   @angular-devkit/schematics    : 13.0.4
   @angular/cli                  : 13.0.4
   @ionic/angular-toolkit        : 5.0.3
   
   In a very simple app, in this example: https://www.positronx.io/ionic-cordova-geolocation-and-geocoder-tutorial-with-examples/
   
   when I use "ionic serve" app in browser is ok, but when I launch it on my device, using "ionic cordova run android", I obtain "Position error:application does not have sufficient geolocation permission" even if I allow geolocation in app preferences.

So I can't obtain latitude and longitude. Any suggestion?

**Comment by jcesarmobile** [comment]
Can you provide a sample app where the issue can be reproduced?

**Comment by jcesarmobile** [comment]
Closing since there was no response
