### ISSUE TITLE
[question android api 31 32] approximate access to geolocation for getCurrentLocation

### ISSUE THREAD

**Issue by expcapitaldev** [apache/cordova-plugin-geolocation#254]
So, we know some additional information about bugs/specific/unexpected cases on android with approximate access, see https://github.com/apache/cordova-plugin-geolocation/pull/250. It is real good description for some cases.

It is not relevant to api 30 because we can not get access to approximate level only, issue connected only for api 31>= because we will have two options for access level approximate and precise. And I did not find any unexpected cases on api level 33 too, but looks like need to check Webview version because it is connected to W3C and navigator.getCurrentPosition
I tested on some devices login and found some cases:
on android with api level 31 and 32 

in every time I ask full permission access: COARSE and FINE + add access only for approximate, and only after that try to get navigator.getCurrentLocation (I get permission from diagnostic plugin with latest version, but in all it is not required) 
If user added FULL permission I will ask with enableHighAccuracy true, if second case with enableHighAccuracy: false.
enableHighAccuracy: false only for api 31>=.

1. ask permission
2. FULL access
3. ask enableHighAccuracy: true
4. no any timeout/errors

next case:

1. ask permission
2. approximate access only
3. ask enableHighAccuracy: false
4. timeout/errors in next cases: (but if kill app and reopen without unexpected cases)

- google emulator webview 91, api 31/32 approximate + getCurrentLocation + enableHighAccuracy false = timeout error
- samsung webview 104 api 31 approximate + getCurrentLocation + enableHighAccuracy false =  result with additional popup about access to precise (for 31 api we ask two permissions, it is expected flow) but we can get coordinates without error
- xiaomi 30 approximate/precise + getCurrentLocation + enableHighAccuracy false/true = timeout error
- sm-g980F webview 106  api 31 approximate + getCurrentLocation + enableHighAccuracy false =  result without additional popup, but we ask 2 permissions, and we can get coordinates without error

- SM-G781B webview 106  api 31 approximate + getCurrentLocation + enableHighAccuracy false =  result without additional popup, but we ask 2 permissions, and we can get coordinates without error

- SM-G781B 106 api 31 approximate + getCurrentLocation + enableHighAccuracy false =  result without additional popup, , but we ask 2 permissions  and we can get coordinates without error

I can get coordinates if kill app and reopen with approximate access + enableHighAccuracy false .

Summary:
Looks like bug why we can not get coordinates with enableHighAccuracy: false on api 31 and 32 connected for:
- emulator only
- google devices only
- webview version from 91-106 and issue fixed in webview version 104+

I would appreciate any additional information on this matter.
Goal: understanding the nuances and creating a universal flow, including the features of the work of different api versions
As long as there is a plan, it is mandatory to get accurate access to geolocation for api 31 and 32, and only then can you already access "getCurrentPosition" and be sure that you should get the coordinates.

Can not find any changelog for chromium(webview) on android

**Comment by expcapitaldev** [comment]
I can find only https://bugs.chromium.org/p/chromium/issues/list?q=getCurrentPosition&can=2 but we can see only https://bugs.chromium.org/p/chromium/issues/detail?id=1269362&q=getCurrentPosition&can=2

**Comment by expcapitaldev** [comment]
update:
google emulator webview 91, api **32** approximate + getCurrentLocation + enableHighAccuracy false = results,
can not understand why it  did not work in previous time

**Comment by expcapitaldev** [comment]
update: now it is relevant for android api level 32 again
google emulator webview 91, api 32 approximate + getCurrentLocation + enableHighAccuracy false = timeout error

**Comment by expcapitaldev** [comment]
@dpa99c sorry that I tagged you, maybe you have any ideas?

**Comment by breautek** [comment]
This hasn't been released yet, but this sounds related to a recent PR that has been merged (commit https://github.com/apache/cordova-plugin-geolocation/commit/9187204e27afd67fa
049ff59b90bf8fc4eba1b11 & PR https://github.com/apache/cordova-plugin-geolocation/pull/250)

You can test against the dev version of this plugin by issueing the following commands:

```
cordova plugin remove cordova-plugin-geolocation
cordova plugin add https://github.com/apache/cordova-plugin-geolocation.git
```

**Comment by expcapitaldev** [comment]
yep, I tested from master/main branch
