### ISSUE TITLE
Next version release

### ISSUE THREAD

**Issue by byronigoe** [apache/cordova-plugin-geolocation#258]
### Issue Type

- [ ] Bug Report
- [ ] Feature Request
- [x] Support Question

## Description
When will a new version be tagged and released to NPM?

## Information
I would like to use a new release with the fixes in https://github.com/apache/cordova-plugin-geolocation/pull/250

### Environment, Platform, Device

Android

### Version information

cordova-android 11.0.0
cordova-plugin-geolocation 4.1.0

## Checklist

- [x] I searched for already existing GitHub issues about this
- [x] I updated all Cordova tooling to their most recent version
- [x] I included all the necessary information above

**Comment by chanchowancho** [comment]
I'd like to +1 this issue/request - our company is using this plugin for geolocation and would love to have the #250 fix released.

**Comment by breautek** [comment]
> I'd like to +1 this issue/request - our company is using this plugin for geolocation and would love to have the #250 fix released.

I hear yah. I use this plugin at work too. Due to the volunteer nature of Apache plugin, I can't give any real ETA, but I am spending some volunteer time working on this.

Currently I'm trying to stablize the CI before release.
