### ISSUE TITLE
Description String override in android as in iOS

### ISSUE THREAD

**Issue by jpoloram** [apache/cordova-plugin-geolocation#259]
# Feature Request
We should have the ability to override the request text for geolocation access.

## Motivation Behind Feature
Google play store now wants the description to meet a specific format to accept the app for publishing.

## Feature Description
The description text must meet the formats below as written by Google:

To meet the policy requirements, it is recommended that you reference one of the following example formats, the second example includes the use of location for ads (choose the most relevant phrasing):

“[This app] collects location data to enable ["feature"], ["feature"], & ["feature"] even when the app is closed or not in use.” 
“[This app] collects location data to enable ["feature"], ["feature"], & ["feature"] even when the app is closed or not in use and it is also used to support advertising.”

## Alternatives or Workarounds
So far I have found no workaround.

**Comment by hvaughan3** [comment]
I believe this is just a recommendation and not a requirement. The following link mentions the text as a "recommended" description. Have you see this change to a required description somewhere?

https://support.google.com/googleplay/android-developer/answer/9799150?hl=en#zippy=%2Cdisclosure-statement-requirements%2Crecommended-disclosure-format

**Comment by jpoloram** [comment]
They aren't allowing the app onto the google play store without it.  The format is recommended but the context i.e. explaining that you are using the geolocation in the background and the purpose it serves within the app.

**Comment by breautek** [comment]
Android doesn't have request text in the same way iOS does. The permission model is not configurable. That is the system model that the user actually uses to give or deny consent.

Instead, Android gives you some amount of flexibility in how you inform your users. They do have some requirements and is definitely more picky if you have background location enabled or you use location data for analytics/ads, but it can be either a snippet of information on screen, or a dialog just before you call the API.

I'll say that Cordova doesn't really expose a permission API, so producing a dialog jist before showing a request dialog can be difficult but the third party diagnostics plugin can help fill that gap. https://github.com/dpa99c/cordova-diagnostic-plugin

**Comment by jcesarmobile** [comment]
The plugin only prompts for permission, but the prompt you are talking about is something you should prompt before the plugin prompts for permissions, so there is nothing to do on the plugin side, you could use cordova-plugin-dialogs plugin to show that text before using cordova-plugin-geolocation

You can see a video with an explanation about that disclosure text and how it should be presented before requesting the permissions, but it's a different prompt from the permissions prompt

https://www.youtube.com/watch?v=b0I1Xq_iSK4
