### ISSUE TITLE
this.geolocation.clearWatch is not a function

### ISSUE THREAD

**Issue by shouhuori** [apache/cordova-plugin-geolocation#262]
the code:
```typescript
import { Geolocation } from "@ionic-native/geolocation/ngx";

export class AppComponent {
constructor(
    public geolocation: Geolocation
)

watchPos(){
 var watchID = this.geolocation.watchPosition({ maximumAge: 3000, timeout: 5000, enableHighAccuracy: true });
 this.geolocation.clearWatch(watchID);
}
}
```

**Comment by breautek** [comment]
Cordova plugin clobbers `window.navigator.geolocation` namespace.

`this.geolocation.watchPosition` is part of the ionic API. It uses this plugin behind the scenes, but if you're having issue with `this.geolocation` context, you'll need to raise an issue with Ionic.

Closing cause this doesn't appear to be a bug with the Cordova Plugin.
