### ISSUE TITLE
Heading is set to NaN if speed is 0 or null.

### ISSUE THREAD

**Issue by fudom** [apache/cordova-plugin-geolocation#274]
https://github.com/apache/cordova-plugin-geolocation/blob/09e3d893b95838764e8b2d5b7052ff940704fe78/www/Coordinates.js#L53-L61

Why `this.heading = NaN` on !speed? Why not just let heading as it is? And why `NaN` and not `null`? I don't know what the (raw) heading value is on speed 0 or null. But the user can decide to don't use heading if speed is not set. It's just a code review.

**Comment by breautek** [comment]
> Initialize coord's [heading](https://www.w3.org/TR/geolocation/#dom-geolocationcoordinates-heading) attribute in degrees, or null if the implementation cannot provide heading information. If the hosting device is stationary (i.e., the value of the [speed](https://www.w3.org/TR/geolocation/#dom-geolocationcoordinates-speed) attribute is 0), then initialize the [heading](https://www.w3.org/TR/geolocation/#dom-geolocationcoordinates-heading) to NaN.

https://www.w3.org/TR/geolocation/#constructing-a-geolocationposition

The `this.speed === null` might not be according to spec, but if speed is 0, then the device is stationary and by spec heading should be `NaN`, which will match browser implementations.
